# Install dependencies. 
install.packages("cowplot")
install.packages("data.table")
install.packages("devtools")
install.packages("dplyr")
install.packages("ggplot2")
devtools::install_github(repo = "zrmacc/MatrixOps")
install.packages("mvnfast")
install.packages("optparse")
install.packages("Rcpp")
install.packages("RNOmni")
install.packages("SurrogateRegression")
install.packages("tidyr")
install.packages("xtable")
